### ISSUE TITLE
Request for Code Sharing

### ISSUE THREAD

**Issue by haohoang** [anazhaw/Bio-SODA#3]
Hi there, 
I'm a student working on a project similar to yours. I've been following your work for a while now and I'm really impressed with what you've accomplished. I noticed in your README that your project is based on SODA. I'm wondering if you would be open to sharing the source code with me. I'd like to use it as a starting point for my own project and would be happy to contribute to your project in the future.
Regards,

**Comment by dssib** [comment]
Hi, 

Thank you for the interest in SODA - I am however no longer involved in the project directly, I would recommend you contact Prof. Kurt Stockinger for this matter: kurt.stockinger@zhaw.ch.

Ana
